### ISSUE TITLE
Rigger - Design note

### ISSUE THREAD

**Issue by NURabbit** [EGO-Tech/starbase-ships#13]
Decided to pull your ship into the editor and take a look, amazing work
One thing I did was add another 4 mining lasers to the advanced turret mounts on the sides, just copied your own..
ship mines (Only with pulse enabled mind you) MUCH smoother, and IMO provides a nicer experience 🍡

**Comment by NURabbit** [comment]
PS: Keep up the good work, the community needs more devoted builders in the ranks

**Comment by vinteo** [comment]
So 6 lasers total? That would drain the power really fast, even with pulse.

You should try fit another two generators, one on each side, but even then
it will be as slightly underpowered. That would also max out the generators
for the number of chambers. It would need to be done in the designer though
as the space is a bit hard to get to.

**Comment by fackir** [comment]
I removed the front panel and moved it to the side (it interferes with the view very much).... the approach does not always turn off, which led to a collision with an asteroid (the stand with bumper scripts, part of the skin and the rangefinder broke). With partial loading, the deviation from the direct course is very strong ..... (you have to constantly steer) . Added automatic shutdown of lasers + ore collector (by rangefinder) Otherwise, he's just the best!!!!!!!!!
